env:
  global:
    # AWS S3 secrets for artifacts storage
    - ARTIFACTS_BUCKET=hammerspoontravisartifacts
    - secure: "W1awxpwgPSxprZ8/hlMWMM9DDi4CUhJLgCrDdMTpv5WplicuHr/xzD6UWyAlqKAh5Gwti8K1PK0RF4ty0FoTQLUWbIYKkoyvS9BAb4dxXEPFhaWwXUf85ItNvKPzNjCJbUZmnBzBnvLMkIO6bQYP8giu6oAQB5YJzGTrCx5ahnU="
    - secure: "TEL0n7UKwhh7mx5IdLAhWN7GMrznOZb/JiqJfKSTh/134uRdofg6V0ofZC67B7sffRjWeFsHRhCl+qIjheJFY4Z4YYPibG4WJaJJdwUaJHU1ZCrwtq2DpeXzLZ+wdJPlK9Zh4Ssqu6+ilfdzk4yF8ZJ/yK7EyB+GB/Xnx/4ts24="
language: objective-c
osx_image: xcode8.2
before_install:
  - gem install github-markdown
  - gem install xcpretty
  - gem install xcpretty-travis-profiler-formatter
before_script:
  - make docs
script:
  - scripts/travis-build.sh build
  - scripts/travis-build.sh test
after_script:
  - make build/html
after_success:
  - bash <(curl -s https://codecov.io/bash) >$HOME/codecov.log 2>&1
after_failure:
  - tail -500 $HOME/build.log
  - tail -500 $HOME/test.log
notifications:
  irc:
    channels:
      - "irc.freenode.net#hammerspoon"
    template:
      - "%{author} @ %{repository} / %{branch} - Build:#%{build_number} : %{message} - Changes: %{compare_url} - Build details: %{build_url}"
    use_notice: true
    skip_join: true
addons:
  artifacts:
    s3_region: "eu-west-1"
    paths:
      - $HOME/build.log
      - $HOME/test.log
      - $HOME/codecov.log
    target_paths: logs/$TRAVIS_BUILD_NUMBER
    permissions: public
    cache-control: public
    debug: true
