language: objective-c
osx_image: xcode8.2
before_install:
  - gem install github-markdown
  - gem install xcpretty -v 0.2.2
  - gem install xcpretty-travis-profiler-formatter -v 0.0.2
  - defaults write org.hammerspoon.Hammerspoon HSAutoLoadExtensions false
before_script:
  - make docs
xcode_workspace: Hammerspoon.xcworkspace
xcode_scheme: Release
script:
  - xcodebuild -workspace Hammerspoon.xcworkspace -scheme Release build GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
after_script:
  - make build/html
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  irc:
    channels:
      - "irc.freenode.net#hammerspoon"
    template:
      - "%{author} @ %{repository} / %{branch} - Build:#%{build_number} : %{message} - Changes: %{compare_url} - Build details: %{build_url}"
    use_notice: true
    skip_join: true
