language: objective-c
osx_image: xcode7.2
before_install:
  - gem install github-markdown xcpretty-travis-formatter
  - pip install codecov
before_script:
  - make docs
  - sudo sqlite3 /Library/Application\ Support/com.apple.TCC/TCC.db "INSERT INTO access VALUES('kTCCServiceAccessibility','org.hammerspoon.Hammerspoon',0,1,1,NULL,NULL);"
  - sudo sqlite3 /Library/Application\ Support/com.apple.TCC/TCC.db "INSERT INTO access VALUES('kTCCServiceAccessibility','com.apple.dt.Xcode-Helper',0,1,1,NULL,NULL);"
xcode_workspace: Hammerspoon.xcworkspace
xcode_scheme: Release
script:
  - xcodebuild -workspace Hammerspoon.xcworkspace -scheme Release build test | xcpretty -f `xcpretty-travis-formatter`
after_script:
  - make build/html
after_success:
  - codecov
notifications:
  irc:
    channels:
      - "irc.freenode.net#hammerspoon"
    template:
      - "%{author} @ %{repository} / %{branch} - Build:#%{build_number} : %{message} - Changes: %{compare_url} - Build details: %{build_url}"
    use_notice: true
    skip_join: true
